---
- name: create stack user
  user: >
    name=stack
    state=present
    shell=/bin/bash
    home=/opt/stack
    move_home=yes
    groups=sudo

- name: create /home/stack/.ssh
  file: >
    owner=stack
    group=sudo
    mode="go-w"
    path=/opt/stack/.ssh
    state=directory
  
- name: install /home/stack/.ssh/authorized_keys
  copy: >
    owner="stack"
    group="stack"
    mode=600
    src=opt/stack/.ssh/authorized_keys
    dest=/opt/stack/.ssh/authorized_keys
